config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurants#index'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  
  resources :restaurants, shallow: true do 
    resources :reviews do 
      resources :endorsements 
    end
  end

  get 'restaurants' => 'restaurants#index'

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy, autosave: true
	validates :name, length: {minimum: 3}, uniqueness: true

	def average_rating
		return 'N/A' if reviews.none?
		# reviews.inject(0) {|memo,review| memo + review.rating}
		# reviews.inject(0) {|memo,review| memo + review.rating}/reviews.count
		reviews.average(:rating)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	validates :rating, inclusion: (1..5)
	has_many :endorsements
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0,20]
  		# user.name = auth.info.name 
  		# user.image = auth.info.image
  	end
  end

  def self.new_with_session(params, session)
  	super.tap do |user|
  		if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  			user.email = data["email"] if user.email.blank?
  		end
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

	def create
		@review = Review.find(params[:review_id])
		@review.endorsements.create
		redirect_to restaurants_path #what does this mean?
	end
	
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def restaurant_params
		params.require(:restaurant).permit(:name)
	end

	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		# @restaurant = Restaurant.new(restaurant_params)
		@restaurant = Restaurant.new(restaurant_params)
		if @restaurant.save
			redirect_to restaurants_path
		else
			render 'new'
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(restaurant_params)

		redirect_to('/restaurants')
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		flash[:notice] = 'Restaurant deleted successfully'
		redirect_to '/restaurants'
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
#how do those link_to helpers know where to look/how are they made

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = Review.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@restaurant.reviews.create(review_params)
		redirect_to restaurants_path
	end

	def review_params
		params.require(:review).permit(:thoughts, :rating)
	end
	

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else 
			session["devise.facebook_data"]=request.env["omniauth.auth"]
			redirect_to_new_user_registration_url
		end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def star_rating(rating)
		return rating unless rating.respond_to?(:round)
		remainder = (5 - rating)
		'★'*rating.round + '☆'*remainder
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <meta charset="UTF-8"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Sign in", new_user_session_path %>
	<%= link_to "Sign in with facebook", user_omniauth_authorize_path(:facebook) %>
	<%= link_to "Sign up", new_user_registration_path %>
<% end %>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<%= link_to "#{restaurant.name}", restaurant_path(restaurant) %>
		<h3>Average rating: <%= restaurant.average_rating.to_i %></h3>
		<h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
		<%=link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
		<%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>

		<% if restaurant.reviews.any? %>
			<ul>
				<% restaurant.reviews.each do |review| %>
					<p><%= review.endorsements.count %> endorsements</p>
					<li>
						<%= review.thoughts %>, <strong><%= review.rating %></strong>/5
					</li>
				<% end %>
			</ul>
		<% else %>
			<p>No reviews.</p>
		<% end %>

		<%= link_to "Review #{restaurant.name}",new_restaurant_review_path(restaurant) %>
	<% end %>
<% else %>
	<h1>No restaurants yet</h1>
<% end %>

<a href='/restaurants/new'>Add a restaurant</a>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
	<section id='errors' >
		<h2> <%= pluralize(@restaurant.errors.count, "error")%>
			prohibited this restaurant from being saved
		</h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</section>
<% end %>

<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h3>Reviews for <%= @restaurant.name %></h3>

<% if @restaurant.reviews.any? %>
	<ul>
		<% @restaurant.reviews.each do |review| %>
		<li>
			<%= review.thoughts %>, <strong><%= review.rating %></strong>/5
		</li>
		<% end %>
	</ul>
<% else %>
	<p>No reviews.</p>
	<% end %>
	

app/views/reviews/new.html.erb
<%= form_for [@restaurant,@review] do |f| %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>
	<%= f.label :rating %>
	<%= f.select :rating, (1..5) %>
	<%= f.submit 'Leave Review' %>
<% end %>